"""Added url columns to user table

Revision ID: 05e06272adfb
Revises: 722911a11979
Create Date: 2022-11-01 08:02:16.561614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05e06272adfb'
down_revision = '722911a11979'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('customer_image_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('customer_id_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'customer_id_url')
    op.drop_column('users', 'customer_image_url')
    # ### end Alembic commands ###
