"""Added made_by column to transaction table

Revision ID: 0b1a2d868902
Revises: 8575a6addbbd
Create Date: 2022-12-15 00:24:33.475675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b1a2d868902'
down_revision = '8575a6addbbd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('made_by', sa.String(), server_default='admin', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'made_by')
    # ### end Alembic commands ###
