"""change loan expiry date column to timestamp

Revision ID: 0e0542ebd068
Revises: fe942d77b94c
Create Date: 2022-08-23 03:38:04.696513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e0542ebd068'
down_revision = 'fe942d77b94c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
