"""change server default for running in loans table

Revision ID: 17983d081649
Revises: c58f463a3803
Create Date: 2022-08-18 05:05:03.725368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17983d081649'
down_revision = 'c58f463a3803'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('loans', 'running',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('loans', 'running',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###
