"""Add fixed deposit accounts

Revision ID: 5260356ed92d
Revises: eceed9b7fd6a
Create Date: 2023-01-08 08:48:14.039903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5260356ed92d'
down_revision = 'eceed9b7fd6a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fixed_deposit_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_balance', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('payout_date', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cycle', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fixed_deposit_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('cycle', sa.Integer(), server_default='0', nullable=False),
    sa.Column('transaction_type', sa.String(), server_default='None', nullable=False),
    sa.Column('old_balance', sa.Integer(), server_default='0', nullable=False),
    sa.Column('new_balance', sa.Integer(), server_default='0', nullable=False),
    sa.Column('made_by', sa.String(), server_default='self', nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['fixed_deposit_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fixed_deposit_transactions')
    op.drop_table('fixed_deposit_accounts')
    # ### end Alembic commands ###
