"""auto_tables

Revision ID: 60ea7a034f6e
Revises: 371244eae8bf
Create Date: 2022-08-13 06:22:38.495997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60ea7a034f6e'
down_revision = '17a782b7ca47'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.String(), nullable=True),
    sa.Column('home_address', sa.String(), nullable=False),
    sa.Column('work_address', sa.String(), nullable=False),
    sa.Column('nature_of_business', sa.String(), nullable=False),
    sa.Column('contact_one', sa.Integer(), nullable=False),
    sa.Column('contact_two', sa.Integer(), nullable=True),
    sa.Column('requested_loan_amount', sa.Integer(), nullable=False),
    sa.Column('guarantor_one', sa.String(), nullable=False),
    sa.Column('guarantor_two', sa.String(), nullable=True),
    sa.Column('guarantor_one_contact', sa.Integer(), nullable=False),
    sa.Column('guarantor_two_contact', sa.Integer(), nullable=False),
    sa.Column('guarantor_two_relationship', sa.String(), nullable=True),
    sa.Column('guarantor_one_relationship', sa.String(), nullable=False),
    sa.Column('customer_id_url', sa.String(), nullable=True),
    sa.Column('customer_image_url', sa.String(), nullable=True),
    sa.Column('business_picture_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=False), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('biodata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.String(), nullable=True),
    sa.Column('home_address', sa.String(), nullable=False),
    sa.Column('work_address', sa.String(), nullable=False),
    sa.Column('customer_contact_one', sa.String(), nullable=False),
    sa.Column('customer_contact_two', sa.String(), nullable=True),
    sa.Column('guarantor_one', sa.String(), nullable=False),
    sa.Column('guarantor_two', sa.String(), nullable=True),
    sa.Column('guarantor_one_contact', sa.String(), nullable=False),
    sa.Column('guarantor_two_contact', sa.String(), nullable=True),
    sa.Column('guarantor_two_relationship', sa.String(), nullable=True),
    sa.Column('guarantor_one_relationship', sa.String(), nullable=False),
    sa.Column('customer_id_url', sa.String(), nullable=True),
    sa.Column('customer_image_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=False), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_principle', sa.Integer(), nullable=False),
    sa.Column('loan_interest_rate', sa.Integer(), nullable=False),
    sa.Column('loan_interest', sa.Integer(), nullable=False),
    sa.Column('loan_payable', sa.Integer(), nullable=False),
    sa.Column('loan_balance', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=False), server_default=sa.text('now()'), nullable=False),
    sa.Column('loan_period', sa.String(), nullable=False),
    sa.Column('expiry_date', sa.TIMESTAMP(timezone=False), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('running', sa.Boolean(), server_default='True', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=False), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('payments')
    op.drop_table('loans')
    op.drop_table('biodata')
    op.drop_table('applications')
    # ### end Alembic commands ###
