"""Add transaction type to groupPayments table

Revision ID: 64a3d614a7b9
Revises: 5dbea6cb9933
Create Date: 2022-11-07 01:14:09.135357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64a3d614a7b9'
down_revision = '5dbea6cb9933'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_payments', sa.Column('transaction_type', sa.String(), server_default='None', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group_payments', 'transaction_type')
    # ### end Alembic commands ###
