"""remove timezone from timestamp in column created_at table loans

Revision ID: 78727153103e
Revises: 17983d081649
Create Date: 2022-08-19 23:36:45.712788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78727153103e'
down_revision = '17983d081649'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
