
"""Add group payee and group_payments table

Revision ID: 7970d0e6d457
Revises: 9ac7a1bc8e5b
Create Date: 2022-11-04 09:13:06.670191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7970d0e6d457'
down_revision = '9ac7a1bc8e5b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payout', sa.Integer(), server_default='0', nullable=False),
    sa.Column('account_balance', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), server_default='0', nullable=False),
    sa.Column('group', sa.Integer(), server_default='0', nullable=False),
    sa.Column('user_id', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cycle', sa.String(), server_default='None', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cycle', sa.String(), server_default='None', nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_payments')
    op.drop_table('payees')
    op.drop_table('groups')
    # ### end Alembic commands ###
