"""Add 2 new columns to payments table

Revision ID: 8575a6addbbd
Revises: 39b9a3c48399
Create Date: 2022-12-14 05:57:50.068321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8575a6addbbd'
down_revision = '39b9a3c48399'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('transaction_type', sa.String(), server_default='None', nullable=False))
    op.add_column('payments', sa.Column('made_by', sa.String(), server_default='None', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'made_by')
    op.drop_column('payments', 'transaction_type')
    # ### end Alembic commands ###
