"""Add balance columns to transaction table

Revision ID: 96ad21325c2e
Revises: e47527e718e7
Create Date: 2022-11-22 11:39:00.407309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96ad21325c2e'
down_revision = 'e47527e718e7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('old_balance', sa.Integer(), server_default='0', nullable=False))
    op.add_column('transactions', sa.Column('new_balance', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'new_balance')
    op.drop_column('transactions', 'old_balance')
    # ### end Alembic commands ###
