"""Add network column to user table

Revision ID: 9ac7a1bc8e5b
Revises: 05e06272adfb
Create Date: 2022-11-03 08:01:23.733500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ac7a1bc8e5b'
down_revision = '05e06272adfb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('network', sa.String(), server_default='other', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'network')
    # ### end Alembic commands ###
