"""change foreign key for group_id in long term transactions

Revision ID: 9bdc4ff1b87d
Revises: b7d468643c06
Create Date: 2023-01-05 07:28:37.409451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bdc4ff1b87d'
down_revision = 'b7d468643c06'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('long_term_group_transactions_group_id_fkey', 'long_term_group_transactions', type_='foreignkey')
    op.create_foreign_key(None, 'long_term_group_transactions', 'long_term_groups', ['group_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'long_term_group_transactions', type_='foreignkey')
    op.create_foreign_key('long_term_group_transactions_group_id_fkey', 'long_term_group_transactions', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
