"""rebuild all tables

Revision ID: a0f38b49b857
Revises: f33013b85019
Create Date: 2022-08-23 04:47:48.963208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0f38b49b857'
down_revision = 'f33013b85019'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('first_name', sa.String(), server_default='None', nullable=False),
    sa.Column('last_name', sa.String(), server_default='None', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.String(), nullable=True),
    sa.Column('home_address', sa.String(), nullable=False),
    sa.Column('work_address', sa.String(), nullable=False),
    sa.Column('nature_of_business', sa.String(), nullable=False),
    sa.Column('contact_one', sa.Integer(), nullable=False),
    sa.Column('contact_two', sa.Integer(), nullable=True),
    sa.Column('requested_loan_amount', sa.Integer(), nullable=False),
    sa.Column('guarantor_one', sa.String(), nullable=False),
    sa.Column('guarantor_two', sa.String(), nullable=True),
    sa.Column('guarantor_one_contact', sa.Integer(), nullable=False),
    sa.Column('guarantor_two_contact', sa.Integer(), nullable=False),
    sa.Column('guarantor_two_relationship', sa.String(), nullable=True),
    sa.Column('guarantor_one_relationship', sa.String(), nullable=False),
    sa.Column('customer_id_url', sa.String(), nullable=True),
    sa.Column('customer_image_url', sa.String(), nullable=True),
    sa.Column('business_picture_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('biodata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.String(), nullable=True),
    sa.Column('home_address', sa.String(), nullable=False),
    sa.Column('work_address', sa.String(), nullable=False),
    sa.Column('customer_contact_one', sa.String(), nullable=False),
    sa.Column('customer_contact_two', sa.String(), nullable=True),
    sa.Column('guarantor_one', sa.String(), nullable=False),
    sa.Column('guarantor_two', sa.String(), nullable=True),
    sa.Column('guarantor_one_contact', sa.String(), nullable=False),
    sa.Column('guarantor_two_contact', sa.String(), nullable=True),
    sa.Column('guarantor_two_relationship', sa.String(), nullable=True),
    sa.Column('guarantor_one_relationship', sa.String(), nullable=False),
    sa.Column('customer_id_url', sa.String(), nullable=True),
    sa.Column('customer_image_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_principle', sa.Integer(), nullable=False),
    sa.Column('loan_interest_rate', sa.Integer(), nullable=False),
    sa.Column('loan_interest', sa.Integer(), nullable=False),
    sa.Column('loan_payable', sa.Integer(), nullable=False),
    sa.Column('loan_balance', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('loan_period', sa.Integer(), nullable=False),
    sa.Column('expiry_date', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('running', sa.Boolean(), server_default='True', nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('loans')
    op.drop_table('biodata')
    op.drop_table('applications')
    op.drop_table('users')
    op.drop_table('admins')
    # ### end Alembic commands ###
