"""Add more columns to group table

Revision ID: a39b32949928
Revises: 96ad21325c2e
Create Date: 2022-11-24 23:26:27.609570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a39b32949928'
down_revision = '96ad21325c2e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('group_admin', sa.Integer(), server_default='0', nullable=False))
    op.add_column('groups', sa.Column('cycle_balance', sa.Integer(), server_default='0', nullable=False))
    op.add_column('groups', sa.Column('cycle_change', sa.Integer(), server_default='0', nullable=False))
    op.add_column('groups', sa.Column('cycle', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'cycle')
    op.drop_column('groups', 'cycle_change')
    op.drop_column('groups', 'cycle_balance')
    op.drop_column('groups', 'group_admin')
    # ### end Alembic commands ###
