"""Add balance columns to table payments

Revision ID: e47527e718e7
Revises: 64a3d614a7b9
Create Date: 2022-11-22 09:57:16.958379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e47527e718e7'
down_revision = '64a3d614a7b9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('old_balance', sa.Integer(), server_default='0', nullable=False))
    op.add_column('payments', sa.Column('new_balance', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'new_balance')
    op.drop_column('payments', 'old_balance')
    # ### end Alembic commands ###
