"""change data type of loan expiry date to timestamp

Revision ID: f33013b85019
Revises: 0e0542ebd068
Create Date: 2022-08-23 04:32:40.042040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f33013b85019'
down_revision = '0e0542ebd068'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
