
"""drop timezone from loans

Revision ID: fe942d77b94c
Revises: 78727153103e
Create Date: 2022-08-19 23:41:41.374827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe942d77b94c'
down_revision = '78727153103e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
